### PR TITLE
Fix the crate parsing order

### LINKED ISSUE #337: cbindgen 0.8.6 stopped producing opaque structs
Tested with the current https://github.com/lu-zero/crav1e

All the structures in `src/lib.rs` aren't emitted anymore.

Everything works in `0.8.4`.

### PR DESCRIPTION
**Pull request by lu-zero**
Since cbindgen ignores the ident namespaces and the expected behavior is
to have it generate bindings for the idents declared in the root crate,
parse first the root crate and then its dependencies.

Fixes #337.

### CODE REVIEW

File: src/bindgen/parser.rs [hunk 1]
```diff
@@ -156,6 +156,27 @@ impl<'a> Parser<'a> {
...
+            None => {
+                // This should be an error, but is common enough to just elicit a warning
+                warn!(
+                    "Parsing crate `{}`: can't find lib.rs with `cargo metadata`.",
+                    pkg.name
+                );
+            }
+        }
+
         // Before we do anything with this crate, we must first parse all of its dependencies.
```
Comment (emilio) [inline src/bindgen/parser.rs]: What makes this not be needed then? If it's not really needed, then the comment should go away.

Comment (lu-zero) [reply src/bindgen/parser.rs]: good catch!

**Comment by emilio** [comment]
r? @Gankro (since you introduced that comment?)

I'd need to audit how stateful our parser is. I suspect most of the cross-referencing stuff happens after we're done with all the crates so this could work, but not sure.
