### PR TITLE
Fix #381

### LINKED ISSUE #381: cbindgen panics parsing sodiumoxide crate
```sh
tmp $ cargo new --lib sodiumoxide-ffi
    Created library `sodiumoxide-ffi` package
tmp $ cd sodiumoxide-ffi/
sodiumoxide-ffi $ cat <<EOF > src/lib.rs 
> use sodiumoxide::crypto::box_::{PublicKey, SecretKey};
> #[no_mangle]
> pub extern fn test(pk: &PublicKey, sk: &SecretKey) {}
> EOF
sodiumoxide-ffi $ cbindgen --version
cbindgen 0.9.0
sodiumoxide-ffi $ RUST_BACKTRACE=1 cbindgen -d
thread 'main' panicked at 'error parsing dependency's target metadata: Error("unexpected token")', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: cbindgen::bindgen::ir::cfg::Cfg::load_metadata
  10: <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
  11: <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter
  12: cbindgen::bindgen::cargo::cargo::Cargo::dependencies
  13: cbindgen::bindgen::parser::Parser::parse_crate
  14: cbindgen::bindgen::parser::Parser::parse_crate
  15: cbindgen::bindgen::parser::Parser::parse_crate
  16: cbindgen::bindgen::parser::Parser::parse_crate
  17: cbindgen::bindgen::parser::Parser::parse_crate
  18: cbindgen::bindgen::parser::Parser::parse_crate
  19: cbindgen::bindgen::parser::parse_lib
  20: cbindgen::bindgen::builder::Builder::generate
  21: cbindgen::main
  22: std::rt::lang_start::{{closure}}
  23: std::panicking::try::do_call
  24: __rust_maybe_catch_panic
  25: std::rt::lang_start_internal
  26: main
sodiumoxide-ffi $ 
```

### PR DESCRIPTION
**Pull request by vtavernier**
As noted by @Benlitz, Cargo metadata supports directly specifying the target name instead of using the `#[cfg]` syntax. We can support this by manually creating the `syn::NestedMeta` node from the target name seen as a string literal.

Includes `literal_target` test for non-regression.

### CODE REVIEW

File: src/bindgen/ir/cfg.rs [hunk 1]
```diff
@@ -124,23 +124,30 @@ impl Cfg {
...
+                    } else {
+                        None
                     }
-                    Cfg::load_single(nested.first().unwrap())
-                } else {
-                    None
                 }
-            })
+                Err(_) =>
+                // Parsing failed using #[cfg], this may be a literal target name
```
Comment (emilio) [inline src/bindgen/ir/cfg.rs:141]: This is quite a weird comment style, fwiw. I would've always done either:

```
Err(_) => {
    // comment
```

Or outside :)

File: src/bindgen/ir/cfg.rs [hunk 2]
```diff
@@ -124,23 +124,30 @@ impl Cfg {
...
-            .as_ref()
-            .map(|target| {
-                syn::parse_str::<syn::Meta>(target)
-                    .expect("error parsing dependency's target metadata")
-            })
-            .and_then(|target| {
-                if let syn::Meta::List(syn::MetaList { path, nested, .. }) = target {
-                    if !path.is_ident("cfg") || nested.len() != 1 {
-                        return None;
+        match &dependency.target {
```
Comment (emilio) [inline src/bindgen/ir/cfg.rs:127]: I would've early-returned here, and deindented the rest of the code, but nbd.

File: src/bindgen/ir/cfg.rs (hunk 1 above)
Comment (vtavernier) [reply src/bindgen/ir/cfg.rs:141]: That's interesting, rustfmt added the braces around the returned expression but placed the comment outside, I didn't notice that :-)
